blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<post_id>[0-9]+)/$', views.post, name='post'),
]

calculator/urls.py
from django.conf.urls import url
from . import views

app_name = 'calculator'
urlpatterns = [
    url(r'^$', views.budget_edit, name='budget_edit'),
    url(r'^base/$', views.base),
    url(r'^add_budget/$', views.add_budget, name='add_budget'),
    url(r'del_budget/$', views.del_budget, name='del_budget'),
]

moneycalc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calculator/', include('calculator.urls')),
    url(r'^', include('register.urls')),
    url(r'^', include('blog.urls')),
]

register/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'registration'
urlpatterns = [
    url(r'^accounts/signup/$', views.register_user, name='sign_up'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=100)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

calculator/models.py
import decimal

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


class Calculator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    budget = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def inc_budget(self, value):
        self.budget += value
        return self.budget

    def dec_budget(self, value):
        self.budget -= value
        return self.budget

    def __str__(self):
        return "{}'s budget".format(self.user)


class BudgetExpenses(models.Model):
    calculator = models.ForeignKey(Calculator, on_delete=models.CASCADE)
    value = models.DecimalField(
        max_digits=10, decimal_places=2, default=0,
        validators=[
            MinValueValidator(decimal.Decimal(0.01), message="Can't be negative")
            ]
         )
    category_choices = (
            ('FD', 'Food'),
            ('CL', 'Clothes'),
            ('EN', 'Entertainment'),
            ('BL', 'Bills'),
            ('OT', 'Other'),
            )
    category = models.CharField(max_length=2, choices=category_choices)
    date = models.DateTimeField(auto_now_add=True)


class BudgetIncome(models.Model):
    calculator = models.ForeignKey(Calculator, on_delete=models.CASCADE)
    value = models.DecimalField(
        max_digits=10, decimal_places=2, default=0,
        validators=[
            MinValueValidator(decimal.Decimal(0.01), message="Can't be negative")
            ]
         )
    category_choices = (
        ('SL', 'Salary'),
        ('DP', 'Deposit'),
        ('OT', 'Other'),
    )
    category = models.CharField(max_length=2, choices=category_choices)
    date = models.DateTimeField(auto_now_add=True)

register/models.py
from django.db import models

# Create your models here.

calculator/forms.py
from django import forms

from .models import BudgetExpenses, BudgetIncome


class CalculatorForm(forms.Form):
        add_to_budget = forms.DecimalField(
            max_digits=12,
            decimal_places=2,
            required=False)
        delete_from_budget = forms.DecimalField(
            max_digits=12,
            decimal_places=2,
            required=False)


class ExpensesForm(forms.ModelForm):
    class Meta:
        model = BudgetExpenses
        exclude = ['calculator', 'date']


class IncomeForm(forms.ModelForm):
    class Meta:
        model = BudgetIncome
        exclude = ['calculator', 'date']

register/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def index(request):
    blog_posts = Post.objects.order_by('-pub_date')
    return render(request,
                  template_name='blog/blog_index.html',
                  context={'blog_posts': blog_posts}
                  )


def post(request, post_id):
    post = get_object_or_404(Post, pk =post_id)
    return render(request,
                  'blog/post.html',
                  context={
                      'post': post,
                  }
                  )

calculator/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Calculator, BudgetExpenses, BudgetIncome
from .forms import CalculatorForm, ExpensesForm, IncomeForm


@login_required
def budget_edit(request):
    calc = Calculator.objects.get_or_create(user_id=request.user.pk)[0]
    expenses = BudgetExpenses.objects.filter(calculator=calc)[::-1]
    income = BudgetIncome.objects.filter(calculator=calc)[::-1]
    inc_form = IncomeForm()
    exp_form = ExpensesForm()
    return render(request, 'calculator/index.html', {
        'inc_form': inc_form,
        'exp_form': exp_form,
        'budget': calc.budget,
        'expenses': expenses,
        'income': income,
        })


def base(request):
    return render(request, 'base.html', {})


def add_budget(request):
    if request.method == 'POST':
        calc = Calculator.objects.get_or_create(user_id=request.user.pk)[0]
        inc_form = IncomeForm(request.POST)
        if inc_form.is_valid():
            value = inc_form.cleaned_data.get('value')
            changes = BudgetIncome(
                calculator=calc,
                value=value,
                category=inc_form.cleaned_data.get('category'),)
            changes.save()
            calc.inc_budget(value)
            calc.save()
            return HttpResponseRedirect(reverse('calculator:budget_edit'))
    else:
        HttpResponseRedirect(reverse('calculator:budget_edit'))
    return HttpResponseRedirect(reverse('calculator:budget_edit'))


def del_budget(request):
    if request.method == 'POST':
        calc = Calculator.objects.get_or_create(user_id=request.user.pk)[0]
        exp_form = ExpensesForm(request.POST)
        if exp_form.is_valid():
            value = exp_form.cleaned_data.get('value')
            changes = BudgetExpenses(
                calculator=calc,
                value=value,
                category=exp_form.cleaned_data.get('category'),)
            changes.save()
            calc.dec_budget(value)
            calc.save()
            return HttpResponseRedirect(reverse('calculator:budget_edit'))
    else:
        HttpResponseRedirect(reverse('calculator:budget_edit'))
    return HttpResponseRedirect(reverse('calculator:budget_edit'))

register/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.urls import reverse

from .forms import RegistrationForm


def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['password1'] and form.cleaned_data['password2']:
                if form.cleaned_data['password1'] == form.cleaned_data['password2']:
                    user = User.objects.create_user(
                        form.cleaned_data['username'],
                        form.cleaned_data['email'],
                        form.cleaned_data['password1'],
                        )
                    user.save()
            return render(request, 'registration/success.html', {})
    else:
        form = RegistrationForm()
    return render(request, 'registration/signup.html', {'form': form})


def profile(request):
    return HttpResponseRedirect(reverse('calculator:budget_edit'))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:index'))

blog/templates/blog/blog_index.html
{% extends "base.html" %}
{% block title %}Blog{% endblock %}

{% block content %}

{% if blog_posts %}
    {% for post in blog_posts%}
        <article class="col-md-8">
            <h1>{{ post.title }}</h1>
            <h6>publicated: {{ post.pub_date }}</h6>
            {% if post.pub_date != post.last_modified %}
                <h6>edited: {{ post.last_modified }}</h6>
            {% endif %}
            <p>{{ post.text }}</p>
        </article>
    {% endfor %}
{% else %}
    <article class="col-md-8">
        <h1>There is no posts here</h1>
    </article>
{% endif %}

{% endblock %}

blog/templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <h2>Author: {{ post.author }}</h2>
    <h3>{{ post.pub_date }}</h3>
    <p><pre>{{ post.text }}</pre></p>

</body>
</html>

calculator/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
		<link rel='icon' href='http://cliparts.co/cliparts/yck/aKA/yckaKAxei.png' type="image/x-icon">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Base{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href='{% url 'blog:index' %}'>Calculator</a>
            </div>
                <ul class="nav navbar-nav">
                    <li><a href='{% url "calculator:budget_edit" %}'>My Calculator <span class='glyphicon glyphicon-piggy-bank'></span></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href='{% url "registration:logout" %}'>Logout <span class='glyphicon glyphicon-log-out'></span></a></li>
                    {% else %}
                    <li><a href="{% url 'registration:sign_up' %}"><span class='glyphicon glyphicon-check'></span> Sign up?</a></li>
                    <li><a href='{% url "registration:login" %}'>Log in <span class='glyphicon glyphicon-log-in'></span></a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                {% block content %}
                <div class="col-md-6">
                    <h1>You forgot to make content block</h1>
                </div>
                {% endblock %}
            </div>
        </div>

    </body>
</html>

calculator/templates/calculator/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Base{% endblock %}</title>
    </head>
    <body>
            <nav class='nav navbar-default'>
                    <div class="navbar-header">
                        <a class="navbar-brand" href='#'>Calculator</a></li>
                    </div>
                    <ul class="nav navbar-nav">
                        <li class="text-center"><a href='#'>Change budget</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                        <li class="text-center"><a href='#'>Log in</a></li>
                        {% else %}
                        <li class="text-center"><a href='#'>Sign up</a></li>
                        {% endif %}
                        <!--<li class="text-center"><a href='#'>Link3</a></li>-->
                    </ul>

            </nav>
        <div class="container">
            <div class="row">
                    {% block content %}
                    <h1>HEADER!!!</h1>
                    {% endblock %}
            </div>
        </div>
    </body>
</html>

calculator/templates/calculator/index.html
{% extends 'base.html' %}

{% block title %}MyBudget{% endblock %}

{% block content %}
    <h3>User: {{ request.user }}</h3>
    <h3>Your budget: {{ budget }}</h3>
    <div class="col-md-5">
        <h3>Income:</h3>
        <form method="post" action="{%url 'calculator:add_budget'%}">
            {% csrf_token %}

            <div class="form-group">
                <label for='id_value'>Value:</label>
                <input class="form-control" id='id_value' name='value' type="number" value="0" step="0.01" required>
            </div>
            <div class="form-group">
                <label for='id_category'>Category:</label>
                <select class="form-control" id="id_category" name="category" required>
                    <option value="SL">Salary</option>
                    <option value="DP">Deposit</option>
                    <option value="OT">Other</option>
                </select>
            </div>
            <button type='submit' class="btn btn-primary">Submit</button>
        </form>
    </div>

    <div class="col-md-5">
        <h3>Expenses:</h3>
        <form method="post" action="{%url 'calculator:del_budget'%}">
            {% csrf_token %}
            <div class="form-group">
                <label for='id_value'>Value:</label>
                <input class="form-control" id='id_value' name="value" type="number" value="0" step="0.01" required>
            </div>
            <div class="form-group">
                <label for='id_category'>Category:</label>
                <select class="form-control" id="id_category" name="category" required>
                    <option value="FD">Food</option>
                    <option value="CL">Clothes</option>
                    <option value="EN">Entertainment</option>
                    <option value="BL">Bills</option>
                    <option value="OT">Other</option>
                </select>
            </div>
            <button type='submit' class="btn btn-primary">Submit</button>
        </form>
        </div>

    {% if income %}
    <table class="table table-hover">
        <caption>Income</caption>
        <thead>
            <tr>
                <th>Value</th>
                <th>Category</th>
                <th>Date</th>
            </tr>
        </thead>
        {% for inc in income %}
            <tr>
                <th>{{ inc.value }} </th>
                <th>{{ inc.get_category_display }}</th>
                <th>{{ inc.date }}</th>
            </tr>
        {% endfor %}
    </table>
    {% else %}
    You have no income yet.
    {% endif %}
    <hr>

    {% if income %}
    <table class="table table-hover">
        <caption>Expenses</caption>
        <thead>
            <tr>
                <th>Value</th>
                <th>Category</th>
                <th>Date</th>
            </tr>
        </thead>
        {% for exp in expenses %}
            <tr>
                <th>{{ exp.value }} </th>
                <th>{{ exp.get_category_display }}</th>
                <th>{{ exp.date }}</th>
            </tr>
        {% endfor %}
    </table>
    {% else %}
    You have no expenses yet.
    {% endif %}
{% endblock %}

calculator/templates/calculator/thanks.html
<!DOCTYPE html>
<head>
    <title>Budget</title>
</head>
<body>
    <h1>Thanks!</h1>
    <a href='{% url "calculator:index" %}'>Back to Budget</a>
</body>